### PR TITLE
Fixed bug when deleting a agenda item with application form

### PR DESCRIPTION
**Pull request by nieka**
#160

### CODE REVIEW

**Comment by otherwise777** [comment]
ik heb de pipeline opnieuw gedraaid, ik denk dat je de pipeline draaide toen ik en marijn de beta server aan het fixen waren

**Comment by otherwise777** [comment]
@nieka er gaat iets mis met het bouwen van de docker image:

`Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Class HTMLPurifier_Language_en_x_test located in ./vendor/ezyang/htmlpurifier/library/HTMLPurifier/Language/classes/en-x-test.php does not comply with psr-0 autoloading standard. Skipping.
Class App\repositories\ApplicationFormRepository\ApplicationFormRowRepository located in ./app/repositories/ApplicationFormRepositories/ApplicationFormRowRepository.php does not comply with psr-4 autoloading standard. Skipping.
Class App\repositories\ApplicationFormRepository\ApplicationFormRowOptionRepository located in ./app/repositories/ApplicationFormRepositories/ApplicationFormRowOptionRepository.php does not comply with psr-4 autoloading standard. Skipping.
Class App\repositories\ApplicationFormRepository\ApplicationFormRepository located in ./app/repositories/ApplicationFormRepositories/ApplicationFormRepository.php does not comply with psr-4 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
In PackageManifest.php line 122:
                         
  Undefined index: name  `

**Comment by otherwise777** [comment]
hmm dit gaat schijnbaar mis voor alle pr's

**Comment by nieka** [comment]
Als ik zoek op de error kom ik de volgende 2 instrasante post hierover tegen: [https://stackoverflow.com/questions/61177995/laravel-packagemanifest-php-undefined-index-name](https://stackoverflow.com/questions/61177995/laravel-packagemanifest-php-undefined-index-name) en [https://github.com/composer/composer/issues/9340](https://github.com/composer/composer/issues/9340)

@wouterbles kan het zijn dat onze build tool al composer 2.0 gebruikt?

**Pull request merged**
